In [1]:
list = [1,2,3]
str(list)

'[1, 2, 3]'

In [ ]:
import pandas as pd
rabiStep = 50
rabiTime = 5000
intensity_data = range(0,100)
time_span = range(rabiStep,rabiTime+rabiStep,rabiStep)
df = pd.DataFrame({'Time': time_span, 'Intensity': intensity_data})
df.to_csv('test.csv', index=False, header=True)

In [6]:
rabiStep = 50
rabiTime = 5000
num_points = int(rabiTime/rabiStep)
init_time = 5000
acq_time = 1000
#ASG
ch1 = [0,20]
ch2 = [0,20]
count = [20]
for i in range(num_points):
    ch1.append(init_time)
    ch1.append(rabiStep*(i+1)+100+acq_time)
    
    ch2.append(0)
    ch2.append(init_time+50)
    ch2.append(rabiStep*(i+1))
    ch2.append(50+acq_time)

    count.append(init_time+100+rabiStep*(i+1))
    count.append(acq_time)
ch1.append(0)
ch1.append(20)
ch2.append(0)
ch2.append(20)
count.append(20)
print(ch1)
print(ch2)
print(count)
print(len(ch1))
print(len(ch2))
print(len(count))
print(sum(ch1))
print(sum(ch2))
print(sum(count))



[0, 20, 5000, 1150, 5000, 1200, 5000, 1250, 5000, 1300, 5000, 1350, 5000, 1400, 5000, 1450, 5000, 1500, 5000, 1550, 5000, 1600, 5000, 1650, 5000, 1700, 5000, 1750, 5000, 1800, 5000, 1850, 5000, 1900, 5000, 1950, 5000, 2000, 5000, 2050, 5000, 2100, 5000, 2150, 5000, 2200, 5000, 2250, 5000, 2300, 5000, 2350, 5000, 2400, 5000, 2450, 5000, 2500, 5000, 2550, 5000, 2600, 5000, 2650, 5000, 2700, 5000, 2750, 5000, 2800, 5000, 2850, 5000, 2900, 5000, 2950, 5000, 3000, 5000, 3050, 5000, 3100, 5000, 3150, 5000, 3200, 5000, 3250, 5000, 3300, 5000, 3350, 5000, 3400, 5000, 3450, 5000, 3500, 5000, 3550, 5000, 3600, 5000, 3650, 5000, 3700, 5000, 3750, 5000, 3800, 5000, 3850, 5000, 3900, 5000, 3950, 5000, 4000, 5000, 4050, 5000, 4100, 5000, 4150, 5000, 4200, 5000, 4250, 5000, 4300, 5000, 4350, 5000, 4400, 5000, 4450, 5000, 4500, 5000, 4550, 5000, 4600, 5000, 4650, 5000, 4700, 5000, 4750, 5000, 4800, 5000, 4850, 5000, 4900, 5000, 4950, 5000, 5000, 5000, 5050, 5000, 5100, 5000, 5150, 5000, 5200, 5000, 52

In [9]:
rabiStep = 50
rabiTime = 5000
num_points = int(rabiTime/rabiStep)
time_span = range(rabiStep,rabiTime+50,rabiStep)
print(list(time_span))

[50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450, 1500, 1550, 1600, 1650, 1700, 1750, 1800, 1850, 1900, 1950, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350, 2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750, 2800, 2850, 2900, 2950, 3000, 3050, 3100, 3150, 3200, 3250, 3300, 3350, 3400, 3450, 3500, 3550, 3600, 3650, 3700, 3750, 3800, 3850, 3900, 3950, 4000, 4050, 4100, 4150, 4200, 4250, 4300, 4350, 4400, 4450, 4500, 4550, 4600, 4650, 4700, 4750, 4800, 4850, 4900, 4950, 5000]


In [15]:
import numpy as np
list = range(0,105)
num_sublists = len(list) // 10
sublists = np.array_split(list[:num_sublists * 10], num_sublists)
sum_result = np.sum(sublists, axis=0)

print(sum_result)
sublists

[450 460 470 480 490 500 510 520 530 540]


[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]),
 array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]),
 array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [3]:
10//4

2

In [4]:
list = [1,2,3,4,5,6,7,8,9,10]
list[0:3]

[1, 2, 3]

In [6]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
import numpy as np
np.zeros(10)
# np.ones(10) + np.ones(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
with open('a.lst', 'r', encoding='Windows-1252') as file:
    lines = file.readlines()

for line in lines:
    # 处理每一行的数据，例如打印它们或进行其他操作
    print(line.strip())  # 去除行尾的换行符并打印每一行的内容

1M
ÿÿð?4@ð?ð?i@Y@ð?@@ô½áóç
#ja.lst@Y@i@4@T@À_À€_ÀI@p§@@@@À_À"@"@`ãFA

In [6]:
import pandas as pd
import numpy as np
list = [1,2,3,4,5,6,6,7,7,7,8,8,9,9,9,0,1,0,1,9,2,8,8,7,6]
data = np.array(list)
print(data)
series = pd.Series(data, name='Name')

series.to_csv('test.csv', index=False, header=True)

[1 2 3 4 5 6 6 7 7 7 8 8 9 9 9 0 1 0 1 9 2 8 8 7 6]
